---
- hosts: localhost
  connection: local
  vars:
    vaultname: testkvstijn
    secret_name: key1
    secret_value: value1

  tasks:
  - name: Get Key Vault Info by name
    azure_rm_keyvault_info:
      resource_group: ansible-kv-test-rg
      name: "{{ vaultname }}"
    register: keyvault

  - name: set KeyVault uri fact
    set_fact: keyvaulturi="{{ keyvault['keyvaults'][0]['vault_uri'] }}"

  #https://github.com/Azure/azure_preview_modules/issues/336
  - name: Create a secret with uri as endpoint
    azure_rm_keyvaultsecret:
      secret_name: "{{ secret_name }}"
      secret_value: "{{ secret_value }}"
      keyvault_uri: "{{ keyvaulturi }}"