---
- hosts: localhost
  connection: local
  vars:
    resource_group: myResourceGroup
    plan_name: appplanstijn
    location: eastus
  
  tasks:
    - name: Create app service plan
      azure_rm_appserviceplan:
        state: absent
        resource_group: "{{ resource_group }}"
        name: "{{ plan_name }}"
        is_linux: true
        number_of_workers: 1
        sku: S2

