---
- hosts: localhost
  connection: local
  collections:
    - azure.azcollection
  vars:
    vault_name: testkvstijn
    secret_name: key3

  tasks:
  - name: Get Key Vault by name
    azure_rm_keyvault_info:
      resource_group: ansible-kv-test-rg
      name: "{{ vault_name }}"
    register: keyvault

  - name: Set key vault URI fact
    set_fact: keyvaulturi="{{ keyvault['keyvaults'][0]['vault_uri'] }}"

  - name: Get secret value
    azure_rm_keyvaultsecret_info:
      vault_uri: "{{ keyvaulturi }}"
      name: "{{ secret_name }}"
    register: kvsecret

  - debug:
      var: kvsecret

  - name: set secret fact
    set_fact: secretvalue="{{ kvsecret['secrets'][0]['secret'] }}"

  - debug:
      var: secretvalue

  - name: Output key vault secret
    debug: 
      msg: "{{ secretvalue }}"