- name: Start Azure VM
  hosts: localhost
  connection: local
  vars:
    resource_group: myResourceGroup
    vm_name: myvm

  tasks:
    - name: Start virtual machine
      azure_rm_virtualmachine:
        resource_group: "{{ resource_group }}"
        name: "{{ vm_name }}"